### ISSUE TITLE
Issue with accelerated graphics on Buster

### ISSUE THREAD

**Issue by gpsamu** [novena-next/docs#23]
Hello.  New Novena owner here.  I received my system yesterday and immediately went through the procedure to upgrade to Buster.  I should note that I did hit the issue which was since addressed in https://github.com/novena-next/docs/issues/22
Prior to the upgrade, I confirmed that accelerated graphics (glxgears) seemed to work well.  However, now I observe some strange behaviour with glxgears. 

When I execute it, it opens a window, but it remains blank (black).  Running with debug enabled I see: 

> root@novena-one:~/glmark2/build/src# LIBGL_DEBUG=​verbose glxgears
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /root/.drirc: No such file or directory.
> libGL: OpenDriver: trying /usr/lib/arm-linux-gnueabihf/dri/tls/etnaviv_dri.so
> libGL: OpenDriver: trying /usr/lib/arm-linux-gnueabihf/dri/etnaviv_dri.so
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /root/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /root/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /root/.drirc: No such file or directory.
> [I]  GPU model:          0x320 (rev 5007) (etna_gpu_new:66)
> [I]  GPU model:          0x2000 (rev 5108) (etna_gpu_new:66)
> [E] get-param (8) failed! -22 (Invalid argument) (get_param:40)
> [E] get-param (9) failed! -22 (Invalid argument) (get_param:40)
> libGL: Using DRI2 for screen 0
> Running synchronized to the vertical refresh.  The framerate should be
> approximately the same as the monitor refresh rate.
> [E] submit failed: -22 (Invalid argument) (flush:211)
> [E] submit failed: -22 (Invalid argument) (flush:211)
> [E] submit failed: -22 (Invalid argument) (flush:211)
> [E] submit failed: -22 (Invalid argument) (flush:211)

Seems to be an underlying issue however: 

> root@novena-one:~/glmark2/build/src# dmesg |grep etnaviv
> [    1.607603] etnaviv gpu-subsystem: bound 134000.gpu (ops gpu_ops)
> [    1.610926] etnaviv gpu-subsystem: bound 130000.gpu (ops gpu_ops)
> [    1.614194] etnaviv gpu-subsystem: bound 2204000.gpu (ops gpu_ops)
> [    1.617404] etnaviv-gpu 134000.gpu: model: GC320, revision: 5007
> [    1.655761] etnaviv-gpu 130000.gpu: model: GC2000, revision: 5108
> [    1.708418] etnaviv-gpu 2204000.gpu: model: GC355, revision: 1215
> [    1.746744] [drm] Initialized etnaviv 1.0.0 20150302 on minor 1
> [  201.507660] [drm:etnaviv_ioctl_gem_submit] *ERROR* cmdstream bo has flag ETNA_BO_CMDSTREAM not set

Have anybody here encountered anything similar?  

Update - 

Moving to the beta 4.13 kernel has somewhat mitigated the issue.  However the Novena screen goes blank when I connect to my HDMI monitor now.  I'm wondering if this has to do with a botched update to Buster?

**Comment by Jookia** [comment]
Hmm, I haven't hit this issue. Are you sure you have all the packages installed, including the xorg armada and xorg config?

**Comment by gpsamu** [comment]
I started the upgrade procedure on a clean install using the original Novena image.  The graphics work properly now.  I have both 2D and 3D acceleration working.

**Comment by Jookia** [comment]
I'm glad!
