### ISSUE TITLE
Kernel module for Novena-RF

### ISSUE THREAD

**Issue by gpsamu** [novena-next/docs#24]
Hello!  

I'm happily running Buster on my Novena system.  I decided to try to see if I can install and get the Novena-RF SDR module working with kernel 4.4.  However the required kernel module novena_rf.ko does not appear to be present.  The one shipped with the Novena Jessie distro won't work as it's for an earlier kernel.  There was a thread about this on the forum: https://www.kosagi.com/forums/viewtopic.php?id=453

Has anybody had any luck?  I've tried to checkout novena-next/linux and tried to apply the patch set novena-next/kernel-patches but didn't get much beyond that.  Not sure if that's what I should he working from. 

Any pointers would be appreciated.

**Comment by Jookia** [comment]
You should use either novena-next/linux OR apply the patch sets to a stable 4.19 kernel or newer.

I'm not sure about novena_rf kernel module. Is there source code for it somewhere?

**Comment by gpsamu** [comment]
Ok thanks for clarifying.  I'm totally stumped at the moment trying to find the source code.  I had novena_rf.ko on my system from Jessie, but that doesn't work with kernel 4.4.  I'm looking at the xobs repos now.

**Comment by Jookia** [comment]
Hmm. Did you try apt-get source?

**Comment by gpsamu** [comment]
Ok it's more clear now.  The module novena_rf.ko comes pre-built for kernel 3.x with the Novena-RF package from here: https://github.com/myriadrf/Novena-RF/tree/master/driver

And there are instructions there on how to rebuild if required.  So I'll close this out for now and run through the procedure they provide.  Apologies for the false alarm.

**Comment by Jookia** [comment]
Please keep us updated if it needs patching.
