### ISSUE TITLE
New debian keyrings packages

### ISSUE THREAD

**Issue by LowMem** [novena-next/docs#27]
Launching first script prompt an error:
```bash
root@novena:~/docs/upgrade_scripts# ./upgrade_1_prep.sh 
--2021-04-09 16:26:21--  http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2019.1_all.deb
Résolution de ftp.us.debian.org (ftp.us.debian.org)… 64.50.236.52, 64.50.233.100, 208.80.154.15, ...
Connexion à ftp.us.debian.org (ftp.us.debian.org)|64.50.236.52|:80… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2021-04-09 16:26:21 erreur 404 : Not Found.
```

**Comment by Jookia** [comment]
Yikes. I'll investigate this tomorrow and update the script accordingly.
Sorry for the inconvenience.

**Comment by LowMem** [comment]
No problem: it is okay to have expired GPG keys when time goes by ! ;-)

Note that I tried to fork to submit a merge request, but github does not allow it to old browser (like the one on my novena ;-) ).
So you can find my fork on https://github.com/LowMem/docs (once novena is updated, I will squash it all and do a proper github fork ;-) ).

Thanks for the big work done !

**Comment by Jookia** [comment]
Thanks for the fix, I had to sign in to my other laptop to merge it. It's really not great that GitHub dropped firefox-esr support.
