### ISSUE TITLE
Upgrade script 3 fails

### ISSUE THREAD

**Issue by anon8675309** [novena-next/docs#31]
After running the first two upgrade scripts (and working around #29), running the third script fails to process the following packages:

```
bluez
avahi-daemon
avahi-dnsconfd
libnss-mdns:armhf
pulseaudio-module-zeroconf
paprefs
```

This can be seen in the error message and confirmed by running `dpkg --configure -a` after running the script.  The first thing to fail is the `bluez` package.  We can see this is because of a problem with the dbus service.

```
Setting up bluez (5.50-1.2~deb10u3) ...
Job for dbus.service failed.
See "systemctl status dbus.service" and "journalctl -xe" for details.
```

Using the suggested `systemctl status dbus.service` we see there's a missing configuration file.

```
dbus[503]: [system] Activating systemd to hand-off: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
dbus[503]: [system] Failed to activate service 'org.freedesktop.hostname1': timed out
dbus[503]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out
dbus[503]: [system] Unable to reload configuration: Failed to open "/etc/dbus-1/system.conf": No such file or directory
dbus-send[3316]: Error org.freedesktop.DBus.Error.FileNotFound: Failed to open "/etc/dbus-1/system.conf": No such file or directory
```

I found a ticket where NixOS [ran into this same thing](https://github.com/NixOS/nixpkgs/issues/16514#issuecomment-244619547) and someone suggested that a reboot would fix this. As gross as that sounds to a hardcore Linux user, I gave it a try and when I came back and ran `dpkg --configure -a` again, it proceeded without error. (Side note: `/etc/dbus-1/system.conf` still doesn't exist, so I'm not sure what that's all about).

Suggested fix: Update the instructions to include a reboot after updating to stretch, but before updating to buster.

While that NixOS thread arguably has a better solution, I like the idea of keeping the instructions as simple as possible, and a reboot meets my definition of simple. A link to the NixOS thread could be included so readers can see why the reboot is there (and if the reader wants to dig in deeper to do their upgrade without rebooting, they can).

**Comment by anon8675309** [comment]
And if I had read the instructions more carefully, I would have seen that the reboot step was already in there.  Sorry for the noise.

**Comment by Jookia** [comment]
Maybe it's worth bolding it or something?
